version: 0.2  # Specifies the version of the buildspec file format

phases:
  install:
    runtime-versions:
      python: 3.8  # Specify the Python version to use
    commands:
      - echo Installing dependencies  # Print a message indicating the installation of dependencies
      - pip install -r requirements.txt  # Install dependencies listed in requirements.txt

  pre_build:
    commands:
      - echo Pre-build phase  # Print a message indicating the pre-build phase

  build:
    commands:
      - ls  # List the files in the current directory for debugging purposes
      - python app/translate.py en es app/index.html  # Run the translation script to translate index.html from English to Spanish
      - aws s3 cp app/es-index.html s3://my-spanish-assets-bucket1/index.html  # Upload the translated Spanish index.html to the Spanish S3 bucket

  post_build:
    commands:
      - echo Post-build phase  # Print a message indicating the post-build phase

artifacts:
  files:
    - '**/*'  # Include all files in the build output
  discard-paths: yes  # Discard the directory structure of the build output