version: 0.2  # Specifies the version of the buildspec file format

phases:
  build:
    commands:
      - ls  # List the files in the current directory for debugging purposes
      - aws s3 sync . s3://my-english-assets-bucket1  # Sync the current directory to the English S3 bucket
      - aws s3 sync . s3://my-spanish-assets-bucket1  # Sync the current directory to the Spanish S3 bucket
      - python translate.py en es index.html  # Run the translation script to translate index.html from English to Spanish
      - aws s3 cp es-index.html s3://my-spanish-assets-bucket1/index.html  # Upload the translated Spanish index.html to the Spanish S3 bucket